### ISSUE TITLE
Running Benchmark in K3d

### ISSUE THREAD

**Issue by leflambeur** [robinbryce/benchblock#1]
Hi guys, been lurking on this project for a while now and been really impressed so far!

I'm wondering if possible you have considered further containerising the setup and loadtest tools

I'd love to be able to run this in k3d for local benchmarking and testing, the value of rapidly generating and benchmarking a local eth/consensys deployment is genuinely invaluable.

Currently I have attempted to run the standard tool and then apply the generated/kustomize manifests directly to the cluster.

However the reliance on the loadgen tools needing direct networking access externally from the cluster is looking like a blocker to me without a fair bit of hackery; and honestly I'm not the best with how these deployments need to look (that's why I'm here!).

I believe that maybe making the loadgen workload that is currently built as a docker swarm into a k8s job so that it can use the k8s overlay network directly would be the most appropriate solution here.

How that job needs to look or is built though I'm not too sure.

Something else it may be worth considering is converting the setup and config generators into K8s Operators. That way the config mgmt can be more cluster centric, logically managed and users may be less prone to hacking the deployments vs just simply submitting a config to the operator to deploy the right type of deployments and jobs.

I think that maybe a more streamlined deployment using more standard k8s operator patterns would be great for promoting adoption!

**Comment by robinbryce** [comment]
That is great feedback. Thanks very much. I'm going to dig into this and see what I can come up with.

**Comment by robinbryce** [comment]
We now have full automation examples using kubernetes jobs and github actions (https://github.com/robinbryce/benchblock/blob/main/.github/workflows/loadtest-on-gcp.yaml). The loadtool still requires a portforward to collect the results. But it only requires one. This is fairly straight forward to manage. As the load is now generated in cluster, the results are more stable and there is no need for the per dlt node portfowardings. Future work may solve the problem of collecting results from the kubernetes job, but I'd like to call this issue closed by release v0.2.0
